### ISSUE TITLE
can't build

### ISSUE THREAD

**Issue by yazidkucrit** [AOSPK/packages_overlay_ThemeIcons#1]
some picture eror like themed_icon_zarchiver.png and other 

Error decode img
java.lang.IllegalStateException: Current state = FLUSHED, new state = CODING_END
	at java.base/java.nio.charset.CharsetDecoder.throwIllegalStateException(CharsetDecoder.java:998)
	at java.base/java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:578)
	at java.base/java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:808)
	at java.base/java.util.zip.ZipCoder.normalizedHashDecode(ZipCoder.java:136)
	at java.base/java.util.zip.ZipCoder$UTF8ZipCoder.normalizedHash(ZipCoder.java:228)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1547)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1267)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1229)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:702)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:241)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:171)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:185)

**Comment by eualexandrerrr** [comment]
Thank you for reporting, fixed
